// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/storage (interfaces: APIStorage)
//
// Generated by this command:
//
//	mockgen -destination internal/handlers/mocks/mock_api_storage.go -package mocks contracts/storage APIStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPIStorage is a mock of APIStorage interface.
type MockAPIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAPIStorageMockRecorder
	isgomock struct{}
}

// MockAPIStorageMockRecorder is the mock recorder for MockAPIStorage.
type MockAPIStorageMockRecorder struct {
	mock *MockAPIStorage
}

// NewMockAPIStorage creates a new mock instance.
func NewMockAPIStorage(ctrl *gomock.Controller) *MockAPIStorage {
	mock := &MockAPIStorage{ctrl: ctrl}
	mock.recorder = &MockAPIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIStorage) EXPECT() *MockAPIStorageMockRecorder {
	return m.recorder
}

// DeleteOriginal mocks base method.
func (m *MockAPIStorage) DeleteOriginal(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOriginal", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOriginal indicates an expected call of DeleteOriginal.
func (mr *MockAPIStorageMockRecorder) DeleteOriginal(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOriginal", reflect.TypeOf((*MockAPIStorage)(nil).DeleteOriginal), ctx, path)
}

// DeleteProcessed mocks base method.
func (m *MockAPIStorage) DeleteProcessed(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessed", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessed indicates an expected call of DeleteProcessed.
func (mr *MockAPIStorageMockRecorder) DeleteProcessed(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessed", reflect.TypeOf((*MockAPIStorage)(nil).DeleteProcessed), ctx, path)
}

// OpenProcessed mocks base method.
func (m *MockAPIStorage) OpenProcessed(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenProcessed", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenProcessed indicates an expected call of OpenProcessed.
func (mr *MockAPIStorageMockRecorder) OpenProcessed(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenProcessed", reflect.TypeOf((*MockAPIStorage)(nil).OpenProcessed), ctx, path)
}

// SaveOriginal mocks base method.
func (m *MockAPIStorage) SaveOriginal(ctx context.Context, id, filename string, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOriginal", ctx, id, filename, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOriginal indicates an expected call of SaveOriginal.
func (mr *MockAPIStorageMockRecorder) SaveOriginal(ctx, id, filename, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOriginal", reflect.TypeOf((*MockAPIStorage)(nil).SaveOriginal), ctx, id, filename, data)
}

// SaveProcessed mocks base method.
func (m *MockAPIStorage) SaveProcessed(ctx context.Context, id, ext string, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProcessed", ctx, id, ext, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProcessed indicates an expected call of SaveProcessed.
func (mr *MockAPIStorageMockRecorder) SaveProcessed(ctx, id, ext, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProcessed", reflect.TypeOf((*MockAPIStorage)(nil).SaveProcessed), ctx, id, ext, data)
}
