// Code generated by MockGen. DO NOT EDIT.
// Source: worker/internal/repo (interfaces: WorkerImageRepo)
//
// Generated by this command:
//
//	mockgen -destination internal/repo/mocks/mock_worker_image_repo.go -package mocks worker/internal/repo WorkerImageRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "contracts/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerImageRepo is a mock of WorkerImageRepo interface.
type MockWorkerImageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerImageRepoMockRecorder
	isgomock struct{}
}

// MockWorkerImageRepoMockRecorder is the mock recorder for MockWorkerImageRepo.
type MockWorkerImageRepoMockRecorder struct {
	mock *MockWorkerImageRepo
}

// NewMockWorkerImageRepo creates a new mock instance.
func NewMockWorkerImageRepo(ctrl *gomock.Controller) *MockWorkerImageRepo {
	mock := &MockWorkerImageRepo{ctrl: ctrl}
	mock.recorder = &MockWorkerImageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerImageRepo) EXPECT() *MockWorkerImageRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorkerImageRepo) Get(ctx context.Context, id string) (model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkerImageRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkerImageRepo)(nil).Get), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockWorkerImageRepo) MarkFailed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockWorkerImageRepoMockRecorder) MarkFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockWorkerImageRepo)(nil).MarkFailed), ctx, id)
}

// MarkReady mocks base method.
func (m *MockWorkerImageRepo) MarkReady(ctx context.Context, id, processedPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReady", ctx, id, processedPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReady indicates an expected call of MarkReady.
func (mr *MockWorkerImageRepoMockRecorder) MarkReady(ctx, id, processedPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReady", reflect.TypeOf((*MockWorkerImageRepo)(nil).MarkReady), ctx, id, processedPath)
}
