// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/storage (interfaces: WorkerStorage)
//
// Generated by this command:
//
//	mockgen -destination internal/repo/mocks/mock_worker_storage.go -package mocks contracts/storage WorkerStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerStorage is a mock of WorkerStorage interface.
type MockWorkerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerStorageMockRecorder
	isgomock struct{}
}

// MockWorkerStorageMockRecorder is the mock recorder for MockWorkerStorage.
type MockWorkerStorageMockRecorder struct {
	mock *MockWorkerStorage
}

// NewMockWorkerStorage creates a new mock instance.
func NewMockWorkerStorage(ctrl *gomock.Controller) *MockWorkerStorage {
	mock := &MockWorkerStorage{ctrl: ctrl}
	mock.recorder = &MockWorkerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerStorage) EXPECT() *MockWorkerStorageMockRecorder {
	return m.recorder
}

// OpenOriginal mocks base method.
func (m *MockWorkerStorage) OpenOriginal(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenOriginal", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenOriginal indicates an expected call of OpenOriginal.
func (mr *MockWorkerStorageMockRecorder) OpenOriginal(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenOriginal", reflect.TypeOf((*MockWorkerStorage)(nil).OpenOriginal), ctx, path)
}

// SaveProcessed mocks base method.
func (m *MockWorkerStorage) SaveProcessed(ctx context.Context, id, ext string, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProcessed", ctx, id, ext, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProcessed indicates an expected call of SaveProcessed.
func (mr *MockWorkerStorageMockRecorder) SaveProcessed(ctx, id, ext, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProcessed", reflect.TypeOf((*MockWorkerStorage)(nil).SaveProcessed), ctx, id, ext, data)
}
