// Code generated by MockGen. DO NOT EDIT.
// Source: worker/internal/service (interfaces: ImageProcessor)
//
// Generated by this command:
//
//	mockgen -destination internal/service/mocks/mock_image_processor.go -package mocks worker/internal/service ImageProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "contracts/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessor is a mock of ImageProcessor interface.
type MockImageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessorMockRecorder
	isgomock struct{}
}

// MockImageProcessorMockRecorder is the mock recorder for MockImageProcessor.
type MockImageProcessorMockRecorder struct {
	mock *MockImageProcessor
}

// NewMockImageProcessor creates a new mock instance.
func NewMockImageProcessor(ctrl *gomock.Controller) *MockImageProcessor {
	mock := &MockImageProcessor{ctrl: ctrl}
	mock.recorder = &MockImageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessor) EXPECT() *MockImageProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockImageProcessor) Process(ctx context.Context, origBytes []byte, job dto.ImageJob) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, origBytes, job)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Process indicates an expected call of Process.
func (mr *MockImageProcessorMockRecorder) Process(ctx, origBytes, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockImageProcessor)(nil).Process), ctx, origBytes, job)
}
