services:
  postgres:
    image: postgres:17
    container_name: postgres-eventbooker
    environment:
      POSTGRES_DB: eventbooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pgdata_eventbooker:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventbooker"]
      interval: 3s
      timeout: 3s
      retries: 10

  migrate:
    build: .
    container_name: eventbooker-migrate
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/app/migrate", "-action", "up"]
    volumes:
      - ./config/docker.yaml:/app/config/local.yaml

  server:
    build: .
    container_name: eventbooker-server
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./config/docker.yaml:/app/config/local.yaml

volumes:
  pgdata_eventbooker:
