services:
  postgres:
    image: postgres:17
    container_name: postgres-comments
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_commenttree:/var/lib/postgresql/data

volumes:
  pgdata_commenttree:
